# Generated by Django 3.0.8 on 2020-07-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curriculum',
            new_name='Hospital',
        ),
    ]
